package com.mdm.equipmentservice.model.entity;

public enum EquipmentStatus {
    UNDER_MAINTENANCE, PENDING_ACCEPT_MAINTENANCE, NEW, IN_USE, BROKEN, INACTIVE, REPAIRING, LIQUIDATED, PENDING_TRANSFER, PENDING_HANDOVER,
    PENDING_ACCEPT_REPAIR, PENDING_REPORT_BROKEN, UNDER_INSPECTION, PENDING_ACCEPT_INSPECTION, PENDING_ACCEPT_LIQUIDATION, PENDING_ACCEPTANCE_TESTING // kết thúc sửa chữa, chờ nghiệm thu
}
